name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 19
            cache: npm
        - run: npm ci
        - run: npm install --no-save @testmo/testmo-cli
        - run: |
            echo "token length: ${#TESTMO_TOKEN}"
            echo "url length: ${#secrets.TESTMO_URL}"

        - run: |
            npx testmo automation:run:submit \
                --instance "$TESTMO_URL" \
                --project-id 2 \
                --name "CARES" \
                --source "unit-tests" \
                --results results/*.xml \
                -- npm run mocha-junit # Note space after --
            env:
            TESTMO_URL: ${{ secrets.TESTMO_URL }}
            TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}